### ISSUE TITLE
Just wanted to know how you created these?

### ISSUE THREAD

**Issue by KParthSingh** [wrinkdater/Posys-Cursors-Improved-by-wrinkdater#4]
I mean i know you improved posys's cursors but he also had to start somewhere. my question is what software do you use to create these? thanks.

**Comment by wrinkdater** [comment]
Hi, KParthSingh
I used RealWorld Cursor Editor mainly to edit .cur files.
Also used Photoshop and AWicons Pro to work with colors (literally when working on 2 or 3 cursors).
The logic of the .inf script I looked up in other cursor-packs, which are freely available on the Internet.
I hope I've fully satisfied your interest.
Thank you for your interest :^)
